/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  Signer,
  utils,
} from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace EntropyStructs {
  export type ProviderInfoStruct = {
    feeInWei: PromiseOrValue<BigNumberish>;
    accruedFeesInWei: PromiseOrValue<BigNumberish>;
    originalCommitment: PromiseOrValue<BytesLike>;
    originalCommitmentSequenceNumber: PromiseOrValue<BigNumberish>;
    commitmentMetadata: PromiseOrValue<BytesLike>;
    uri: PromiseOrValue<BytesLike>;
    endSequenceNumber: PromiseOrValue<BigNumberish>;
    sequenceNumber: PromiseOrValue<BigNumberish>;
    currentCommitment: PromiseOrValue<BytesLike>;
    currentCommitmentSequenceNumber: PromiseOrValue<BigNumberish>;
  };

  export type ProviderInfoStructOutput = [
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    string,
    BigNumber
  ] & {
    feeInWei: BigNumber;
    accruedFeesInWei: BigNumber;
    originalCommitment: string;
    originalCommitmentSequenceNumber: BigNumber;
    commitmentMetadata: string;
    uri: string;
    endSequenceNumber: BigNumber;
    sequenceNumber: BigNumber;
    currentCommitment: string;
    currentCommitmentSequenceNumber: BigNumber;
  };

  export type RequestStruct = {
    provider: PromiseOrValue<string>;
    sequenceNumber: PromiseOrValue<BigNumberish>;
    numHashes: PromiseOrValue<BigNumberish>;
    commitment: PromiseOrValue<BytesLike>;
    blockNumber: PromiseOrValue<BigNumberish>;
    requester: PromiseOrValue<string>;
    useBlockhash: PromiseOrValue<boolean>;
    isRequestWithCallback: PromiseOrValue<boolean>;
  };

  export type RequestStructOutput = [
    string,
    BigNumber,
    number,
    string,
    BigNumber,
    string,
    boolean,
    boolean
  ] & {
    provider: string;
    sequenceNumber: BigNumber;
    numHashes: number;
    commitment: string;
    blockNumber: BigNumber;
    requester: string;
    useBlockhash: boolean;
    isRequestWithCallback: boolean;
  };
}

export interface EntropyEventsInterface extends utils.Interface {
  functions: {};

  events: {
    "ProviderFeeUpdated(address,uint128,uint128)": EventFragment;
    "ProviderUriUpdated(address,bytes,bytes)": EventFragment;
    "Registered(tuple)": EventFragment;
    "Requested(tuple)": EventFragment;
    "RequestedWithCallback(address,address,uint64,bytes32,tuple)": EventFragment;
    "Revealed(tuple,bytes32,bytes32,bytes32,bytes32)": EventFragment;
    "RevealedWithCallback(tuple,bytes32,bytes32,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProviderFeeUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProviderUriUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Registered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Requested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestedWithCallback"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Revealed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RevealedWithCallback"): EventFragment;
}

export interface ProviderFeeUpdatedEventObject {
  provider: string;
  oldFee: BigNumber;
  newFee: BigNumber;
}
export type ProviderFeeUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  ProviderFeeUpdatedEventObject
>;

export type ProviderFeeUpdatedEventFilter =
  TypedEventFilter<ProviderFeeUpdatedEvent>;

export interface ProviderUriUpdatedEventObject {
  provider: string;
  oldUri: string;
  newUri: string;
}
export type ProviderUriUpdatedEvent = TypedEvent<
  [string, string, string],
  ProviderUriUpdatedEventObject
>;

export type ProviderUriUpdatedEventFilter =
  TypedEventFilter<ProviderUriUpdatedEvent>;

export interface RegisteredEventObject {
  provider: EntropyStructs.ProviderInfoStructOutput;
}
export type RegisteredEvent = TypedEvent<
  [EntropyStructs.ProviderInfoStructOutput],
  RegisteredEventObject
>;

export type RegisteredEventFilter = TypedEventFilter<RegisteredEvent>;

export interface RequestedEventObject {
  request: EntropyStructs.RequestStructOutput;
}
export type RequestedEvent = TypedEvent<
  [EntropyStructs.RequestStructOutput],
  RequestedEventObject
>;

export type RequestedEventFilter = TypedEventFilter<RequestedEvent>;

export interface RequestedWithCallbackEventObject {
  provider: string;
  requestor: string;
  sequenceNumber: BigNumber;
  userRandomNumber: string;
  request: EntropyStructs.RequestStructOutput;
}
export type RequestedWithCallbackEvent = TypedEvent<
  [string, string, BigNumber, string, EntropyStructs.RequestStructOutput],
  RequestedWithCallbackEventObject
>;

export type RequestedWithCallbackEventFilter =
  TypedEventFilter<RequestedWithCallbackEvent>;

export interface RevealedEventObject {
  request: EntropyStructs.RequestStructOutput;
  userRevelation: string;
  providerRevelation: string;
  blockHash: string;
  randomNumber: string;
}
export type RevealedEvent = TypedEvent<
  [EntropyStructs.RequestStructOutput, string, string, string, string],
  RevealedEventObject
>;

export type RevealedEventFilter = TypedEventFilter<RevealedEvent>;

export interface RevealedWithCallbackEventObject {
  request: EntropyStructs.RequestStructOutput;
  userRandomNumber: string;
  providerRevelation: string;
  randomNumber: string;
}
export type RevealedWithCallbackEvent = TypedEvent<
  [EntropyStructs.RequestStructOutput, string, string, string],
  RevealedWithCallbackEventObject
>;

export type RevealedWithCallbackEventFilter =
  TypedEventFilter<RevealedWithCallbackEvent>;

export interface EntropyEvents extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EntropyEventsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "ProviderFeeUpdated(address,uint128,uint128)"(
      provider?: null,
      oldFee?: null,
      newFee?: null
    ): ProviderFeeUpdatedEventFilter;
    ProviderFeeUpdated(
      provider?: null,
      oldFee?: null,
      newFee?: null
    ): ProviderFeeUpdatedEventFilter;

    "ProviderUriUpdated(address,bytes,bytes)"(
      provider?: null,
      oldUri?: null,
      newUri?: null
    ): ProviderUriUpdatedEventFilter;
    ProviderUriUpdated(
      provider?: null,
      oldUri?: null,
      newUri?: null
    ): ProviderUriUpdatedEventFilter;

    "Registered(tuple)"(provider?: null): RegisteredEventFilter;
    Registered(provider?: null): RegisteredEventFilter;

    "Requested(tuple)"(request?: null): RequestedEventFilter;
    Requested(request?: null): RequestedEventFilter;

    "RequestedWithCallback(address,address,uint64,bytes32,tuple)"(
      provider?: PromiseOrValue<string> | null,
      requestor?: PromiseOrValue<string> | null,
      sequenceNumber?: PromiseOrValue<BigNumberish> | null,
      userRandomNumber?: null,
      request?: null
    ): RequestedWithCallbackEventFilter;
    RequestedWithCallback(
      provider?: PromiseOrValue<string> | null,
      requestor?: PromiseOrValue<string> | null,
      sequenceNumber?: PromiseOrValue<BigNumberish> | null,
      userRandomNumber?: null,
      request?: null
    ): RequestedWithCallbackEventFilter;

    "Revealed(tuple,bytes32,bytes32,bytes32,bytes32)"(
      request?: null,
      userRevelation?: null,
      providerRevelation?: null,
      blockHash?: null,
      randomNumber?: null
    ): RevealedEventFilter;
    Revealed(
      request?: null,
      userRevelation?: null,
      providerRevelation?: null,
      blockHash?: null,
      randomNumber?: null
    ): RevealedEventFilter;

    "RevealedWithCallback(tuple,bytes32,bytes32,bytes32)"(
      request?: null,
      userRandomNumber?: null,
      providerRevelation?: null,
      randomNumber?: null
    ): RevealedWithCallbackEventFilter;
    RevealedWithCallback(
      request?: null,
      userRandomNumber?: null,
      providerRevelation?: null,
      randomNumber?: null
    ): RevealedWithCallbackEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
