/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBlastPoints,
  IBlastPointsInterface,
} from "../../../../contracts/interfaces/v1/IBlastPoints";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "configurePointsOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "configurePointsOperatorOnBehalf",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBlastPoints__factory {
  static readonly abi = _abi;
  static createInterface(): IBlastPointsInterface {
    return new utils.Interface(_abi) as IBlastPointsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBlastPoints {
    return new Contract(address, _abi, signerOrProvider) as IBlastPoints;
  }
}
